### ISSUE TITLE
Haven't looked through this yet but just had a quick question

### ISSUE THREAD

**Issue by VaasKahnGrim** [Leystryku/LeySourceEngineProxyServ#1]
Basically, out of the box linux compiling supported?

**Comment by Leystryku** [comment]
Yeah, make sure you install the dependencies though

Vaas_Kahn_Grim <notifications@github.com> schrieb am Sa., 9. Mai 2020,
19:37:

**Comment by VaasKahnGrim** [comment]
thanks man :)
