### ISSUE TITLE
Unable to LD_PRELOAD

### ISSUE THREAD

**Issue by Xulua1499** [Leystryku/LeySourceEngineProxyServ#2]
After compiling the module, and loading it with LD_PRELOAD I'm running into 

ERROR: ld.so: object 'dir/leyzyrecl.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

It was compiled on the same system so unsure why it's showing as 32

**Comment by Leystryku** [comment]
Hello,
I've encountered the same thing but don't worry about it. Check in your console after (maybe after joining) and if it prints zyre messages then you know it loaded correctly.

**Comment by Xulua1499** [comment]
It stops printing after a while, so I'm guessing it's working. The other thing now is when running leyzyreserv it will say child is rip and continually restart by the looks

**Comment by Leystryku** [comment]
You're probably not setting a IP right or you don't have the proper key set somewhere.
I'm not sure, you'll have to figure it out yourself

**Comment by Xulua1499** [comment]
Doesn't appear to be anything incorrect, manually running leyzyreworker results in a segmentation fault

```
root@gs1:~/LeySourceEngineProxyServ/leyzyre# ./leyzyreworker 41.125.71.3:27016 27015 27016 960050489 "" 0 "ah" 173.254.241.191
zyre | nodeworker ; src: 41.125.71.3:27016 a2sport: 27015 proxyport: 27016 pwd: 912030489 offset:  ipass: 808465977 extraplayers: 0 customname: ah
Going to query data from: 41.125.71.3:27016
Segmentation fault (core dumped)
```

**Comment by Xulua1499** [comment]
https://github.com/Leystryku/LeySourceEngineProxyServ/blob/a808926089d65148be2566774955bf588d45495e/leyzyrenodeworker/a2s.cpp#L311

Here is where it's failing, something with the ipdb.mmdb I guess? Not sure if I'm using the right one as they offer a bunch of them. Currently using GeoIP2 country

**Comment by Leystryku** [comment]
that might be the cause, try around and you'll figure, you're getting closer at least.

**Comment by Leystryku** [comment]
also removing that line, thats debug stuff, that might be where your segfault comes from

**Comment by Xulua1499** [comment]
All working, thanks for the help :)
