### ISSUE TITLE
 leyzyreworker error parameters

### ISSUE THREAD

**Issue by subzer99** [Leystryku/LeySourceEngineProxyServ#4]
Hi very good, I loved this project and I will give you all the credits, what if I have this problem that when trying to execute as it says in the title "leyzyreworker", it throws me Segmentation fault (core dumped)

**Comment by subzer99** [comment]
https://ibb.co/TcXs5rd Here I leave an image for you to see

**Comment by Leystryku** [comment]
The software does not work that way, you can not just start a worker on it's own without the managing system.
