### ISSUE TITLE
leyzyremodule.cpp Line 992 and 1001 issue, listfilewrite isn't defined prior to use

### ISSUE THREAD

**Issue by VaasKahnGrim** [Leystryku/LeySourceEngineProxyServ#7]
Simple fix, had somebody open an issue on one of my github repos asking for help. Figured I'd pass the info along after helping them figure out the issue they were having.

Basically just adding this above the sendto function fixes it:

```cpp
steady_clock::time_point lastfilewrite = steady_clock::now();
```

**Comment by Leystryku** [comment]
Hey,

Could you put your code in a PR?
I'll merge it then

**Comment by VaasKahnGrim** [comment]
done, also I hate github for being an annoying interface

**Comment by Leystryku** [comment]
Solved https://github.com/Leystryku/LeySourceEngineProxyServ/pull/9
